services:
  - type: web
    name: nba-playoff
    env: node
    buildCommand: npm install --prefix client && npm run build --prefix client && rm -rf server/build && cp -r client/build server/build && npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
