// Maps ESPN English team names → Hebrew names used in the app
const ESPN_TO_HEBREW = {
  'Boston Celtics':          'בוסטון סלטיקס',
  'Oklahoma City Thunder':   'אוקלהומה סיטי',
  'Cleveland Cavaliers':     'קליבלנד קאבלירס',
  'Los Angeles Lakers':      'לוס אנגלס לייקרס',
  'Denver Nuggets':          'דנבר נאגטס',
  'Golden State Warriors':   'גולדן סטייט ווריוורס',
  'Milwaukee Bucks':         'מילווקי באקס',
  'Sacramento Kings':        'סקרמנטו קינגס',
  'New York Knicks':         'ניו יורק ניקס',
  'Memphis Grizzlies':       'ממפיס גריזליס',
  'Miami Heat':              'מיאמי היט',
  'Los Angeles Clippers':    'לוס אנגלס קליפרס',
  'Minnesota Timberwolves':  'מינסוטה טימברוולבס',
  'Houston Rockets':         'יוסטון רוקטס',
  'Indiana Pacers':          'אינדיאנה פייסרס',
  'Orlando Magic':           'אורלנדו מגיק',
  'Detroit Pistons':         'דטרויט פיסטונס',
  'Atlanta Hawks':           'אטלנטה הוקס',
  'Chicago Bulls':           'שיקאגו בולס',
  'Dallas Mavericks':        'דאלאס מאבריקס',
  'Phoenix Suns':            'פיניקס סאנס',
  'Philadelphia 76ers':      'פילדלפיה',
  'Toronto Raptors':         'טורונטו ראפטורס',
  'Brooklyn Nets':           'ברוקלין נטס',
  'Washington Wizards':      'וושינגטון ווויזרדס',
  'Charlotte Hornets':       'שרלוט הורנטס',
  'San Antonio Spurs':       'סן אנטוניו ספרס',
  'New Orleans Pelicans':    'ניו אורלינס פליקנס',
  "Utah Jazz":               "יוטה ג'אז",
  'Portland Trail Blazers':  'פורטלנד טרייל בלייזרס',
};

module.exports = ESPN_TO_HEBREW;
